# permissions for end users to edit eipbindings.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: eipbinding-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: kube-eip
    app.kubernetes.io/part-of: kube-eip
    app.kubernetes.io/managed-by: kustomize
  name: eipbinding-editor-role
rules:
- apiGroups:
  - extension.my.domain
  resources:
  - eipbindings
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - extension.my.domain
  resources:
  - eipbindings/status
  verbs:
  - get
