// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v5.26.1
// source: pkg/protoc/admin/admin.proto

package admin

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TotpSecReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *TotpSecReq) Reset() {
	*x = TotpSecReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_protoc_admin_admin_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TotpSecReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TotpSecReq) ProtoMessage() {}

func (x *TotpSecReq) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_protoc_admin_admin_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TotpSecReq.ProtoReflect.Descriptor instead.
func (*TotpSecReq) Descriptor() ([]byte, []int) {
	return file_pkg_protoc_admin_admin_proto_rawDescGZIP(), []int{0}
}

type TotpSecRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Secret string `protobuf:"bytes,1,opt,name=secret,proto3" json:"secret,omitempty"`
	Digits int32  `protobuf:"varint,2,opt,name=digits,proto3" json:"digits,omitempty"`
	Period int32  `protobuf:"varint,3,opt,name=period,proto3" json:"period,omitempty"`
}

func (x *TotpSecRsp) Reset() {
	*x = TotpSecRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_protoc_admin_admin_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TotpSecRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TotpSecRsp) ProtoMessage() {}

func (x *TotpSecRsp) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_protoc_admin_admin_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TotpSecRsp.ProtoReflect.Descriptor instead.
func (*TotpSecRsp) Descriptor() ([]byte, []int) {
	return file_pkg_protoc_admin_admin_proto_rawDescGZIP(), []int{1}
}

func (x *TotpSecRsp) GetSecret() string {
	if x != nil {
		return x.Secret
	}
	return ""
}

func (x *TotpSecRsp) GetDigits() int32 {
	if x != nil {
		return x.Digits
	}
	return 0
}

func (x *TotpSecRsp) GetPeriod() int32 {
	if x != nil {
		return x.Period
	}
	return 0
}

var File_pkg_protoc_admin_admin_proto protoreflect.FileDescriptor

var file_pkg_protoc_admin_admin_proto_rawDesc = []byte{
	0x0a, 0x1c, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x2f, 0x61, 0x64, 0x6d,
	0x69, 0x6e, 0x2f, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x22, 0x0c, 0x0a, 0x0a, 0x54, 0x6f, 0x74, 0x70, 0x53, 0x65,
	0x63, 0x52, 0x65, 0x71, 0x22, 0x54, 0x0a, 0x0a, 0x54, 0x6f, 0x74, 0x70, 0x53, 0x65, 0x63, 0x52,
	0x73, 0x70, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x65, 0x63, 0x72, 0x65, 0x74, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x73, 0x65, 0x63, 0x72, 0x65, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x64, 0x69,
	0x67, 0x69, 0x74, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x64, 0x69, 0x67, 0x69,
	0x74, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x70, 0x65, 0x72, 0x69, 0x6f, 0x64, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x06, 0x70, 0x65, 0x72, 0x69, 0x6f, 0x64, 0x32, 0x3a, 0x0a, 0x05, 0x41, 0x64,
	0x6d, 0x69, 0x6e, 0x12, 0x31, 0x0a, 0x07, 0x54, 0x6f, 0x74, 0x70, 0x53, 0x65, 0x63, 0x12, 0x12,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x2e, 0x54, 0x6f, 0x74, 0x70, 0x53, 0x65, 0x63, 0x52,
	0x65, 0x71, 0x1a, 0x12, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x2e, 0x54, 0x6f, 0x74, 0x70,
	0x53, 0x65, 0x63, 0x52, 0x73, 0x70, 0x42, 0x32, 0x5a, 0x30, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62,
	0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6c, 0x75, 0x63, 0x68, 0x65, 0x6e, 0x67, 0x30, 0x31, 0x32, 0x37,
	0x2f, 0x6b, 0x75, 0x62, 0x65, 0x2d, 0x65, 0x69, 0x70, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x63, 0x2f, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_pkg_protoc_admin_admin_proto_rawDescOnce sync.Once
	file_pkg_protoc_admin_admin_proto_rawDescData = file_pkg_protoc_admin_admin_proto_rawDesc
)

func file_pkg_protoc_admin_admin_proto_rawDescGZIP() []byte {
	file_pkg_protoc_admin_admin_proto_rawDescOnce.Do(func() {
		file_pkg_protoc_admin_admin_proto_rawDescData = protoimpl.X.CompressGZIP(file_pkg_protoc_admin_admin_proto_rawDescData)
	})
	return file_pkg_protoc_admin_admin_proto_rawDescData
}

var file_pkg_protoc_admin_admin_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_pkg_protoc_admin_admin_proto_goTypes = []interface{}{
	(*TotpSecReq)(nil), // 0: protoc.TotpSecReq
	(*TotpSecRsp)(nil), // 1: protoc.TotpSecRsp
}
var file_pkg_protoc_admin_admin_proto_depIdxs = []int32{
	0, // 0: protoc.Admin.TotpSec:input_type -> protoc.TotpSecReq
	1, // 1: protoc.Admin.TotpSec:output_type -> protoc.TotpSecRsp
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pkg_protoc_admin_admin_proto_init() }
func file_pkg_protoc_admin_admin_proto_init() {
	if File_pkg_protoc_admin_admin_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pkg_protoc_admin_admin_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TotpSecReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_protoc_admin_admin_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TotpSecRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pkg_protoc_admin_admin_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_protoc_admin_admin_proto_goTypes,
		DependencyIndexes: file_pkg_protoc_admin_admin_proto_depIdxs,
		MessageInfos:      file_pkg_protoc_admin_admin_proto_msgTypes,
	}.Build()
	File_pkg_protoc_admin_admin_proto = out.File
	file_pkg_protoc_admin_admin_proto_rawDesc = nil
	file_pkg_protoc_admin_admin_proto_goTypes = nil
	file_pkg_protoc_admin_admin_proto_depIdxs = nil
}
